### ISSUE TITLE
Minimize button works the first time but not thereafter

### ISSUE THREAD

**Issue by lf-** [kraxarn/spotify-qt#103]
### System information

```
ABI: x86_64-little_endian-lp64
App version: v3.6-dev (678c408d) - lib v0.4
Current desktop: KDE
D-Bus support: Yes
Device: tail-bot (Computer)
Kernel: linux 5.11.16-arch1-1
Product: Arch Linux
Qt version: 5.15.2
```

### Detailed information

Since I updated to a version with the integrated top bar that has window controls and also media controls, it seems that I can minimize spotify-qt once with the menu bar item, then when I bring it back up from my KDE bottom bar, when I press the minimize button on the window again,  it won't minimize the window until the app is restarted. 

It also seems to happen if I do the first minimization by right clicking the top bar and selecting minimize: after the first time, neither the right click menu option nor the minimize control on the top right will minimize the window. I can minimize the window by clicking on the icon in the KDE bottom bar as many times as I'd like. Interestingly, if I start the app, then minimize the window and restore it by clicking the KDE bar twice, the minimize button on the window will work once before failing again until the app is relaunched like in the other scenarios.

**Comment by kraxarn** [comment]
Still haven't been able to reproduce this, but hopefully it was fixed by b8fbaf2e48d26e9a872cbf78b7e286af5e855545 or something else. If not, are you on Wayland or something? Did you use the snap, or did you compile it yourself?

**Comment by lf-** [comment]
Just rebuilt it on b08e33e6dfcffd9b6819c2a22d3422a80a42c35f and it's still reproducible on my system both on the version I packaged and the version I built from source. However, I have something interesting for you:

With this patched onMinimize:

```c++
void MainToolBar::onMinimize(bool /*checked*/)
{
	auto *mainWindow = MainWindow::find(parentWidget());
	std::cout << "onMinimize MainToolBar\n";
	std::cout << "windowState " << mainWindow->windowState() << "\n";
	std::cout.flush();
	mainWindow->setWindowState(Qt::WindowMinimized);
}
```

I got this:

```
onMinimize MainToolBar
windowState 0
onMinimize MainToolBar
windowState 1
onMinimize MainToolBar
windowState 1
onMinimize MainToolBar
windowState 1
```

So it thinks it's still minimized after being restored by clicking the bottom bar in KDE! I don't know anything about Qt, but this seems weird...

I am on X11 KDE 21.04.2.

**Comment by kraxarn** [comment]
Sounds more like a Qt bug in that case tbh xd
Very hack-y, but could you try:
```cpp
void MainToolBar::onMinimize(bool /*checked*/)
{
	auto *mainWindow = MainWindow::find(parentWidget());
	mainWindow->setWindowState(Qt::WindowNoState);
	mainWindow->setWindowState(Qt::WindowMinimized);
}
```
Sounds like a "safe" workaround, as it shouldn't be possible to minimize an already minimized window.

**Comment by lf-** [comment]
Seems to work, sent you a PR.

**Comment by lf-** [comment]
Filed upstream: https://bugreports.qt.io/browse/QTBUG-95781
